### ISSUE TITLE
Broken links?

### ISSUE THREAD

**Issue by davetapley** [storj/docs#169]
Assuming this repo is https://docs.storj.io,
then e.g. https://docs.storj.io/dcs/api-reference/storj-client-libraries/ has 'Broken Reference':

<img width="945" alt="Screen Shot 2022-02-18 at 2 44 04 PM" src="https://user-images.githubusercontent.com/48232/154765380-13cbc97b-ac44-4e6e-b992-80e3c64ee175.png">

**Comment by ifraixedes** [comment]
They were fixed in commit 7f733d468c9cac9937a7dc422a0876823070a365
