### ISSUE TITLE
How-To- to post - it's how to hot rod your performance

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#171]
https://docs.google.com/document/d/1lNPsmTqpf2yIzNtAys4baHC2OveJ8oYYxOYvSmC1H2w/edit

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/PH8A6aKTELZVucJHTeMn/how-tos/how-to-hod-rod-file-transfer-performance-on-storj-dcs

**Comment by heunland** [comment]
made some edits to fix grammar and merged
