### ISSUE TITLE
Replace copy paste of s3-compatibility with direct link to GitHub

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#172]
https://docs.storj.io/dcs/api-reference/s3-compatible-gateway/supported-s3-commands/ have a limited content from 
https://github.com/storj/gateway-st/blob/main/docs/s3-compatibility.md and it's outdated.

We need to link directly to the documentation in the repo.

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/stI7EBLnQfAUPe5P1B2G/concepts/s3-compatibility

**Comment by heunland** [comment]
reviewing now

**Comment by heunland** [comment]
reviewed and merged
