### ISSUE TITLE
Remove Gateway MT from mention on hosting a static website

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#173]
https://docs.storj.io/dcs/how-tos/host-a-static-website/
> We recommend using the Uplink CLI with Gateway MT but you may also use [...]

`uplink share --url` doesn't really do anything useful for the Gateway MT despite creating an access key. That access key is marked public so the intention is for it to work with linksharing.

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/TJ8VHbjb7gH9RtwK0aAd/how-tos/host-a-static-website

**Comment by heunland** [comment]
Reviewed and merged
