### ISSUE TITLE
Replace uplinkng to uplink in Download page

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#174]
https://docs.storj.io/dcs/downloads/download-uplink-cli/

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/RXRrOuF9anXIPabZGPAH/downloads/download-uplink-cli

**Comment by heunland** [comment]
I reviewed this and merged but please note that https://github.com/storj/storj/releases/download/v1.49.5/uplink_darwin_amd64.zip binary does not exist (yet?) -> should this default to the previous one if the new binary doesn't exist yet? I was reading that we are building the binaries for Mac manually?

**Comment by heunland** [comment]
@stefanbenten confirmed that the problem with the Mac binary should be resolved with the next release
