### ISSUE TITLE
Update instruction for Rclone

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#176]
***This ticket was escalated from Zendesk by Aleksey Leonov:***

  **Ticket:** [#16035](https://storj.zendesk.com/agent/tickets/16035)
  **Type:** Ticket
  **Priority:** -
  **Requester:** Visual
  **Organization:** -
  **Assignee:** Aleksey Leonov
***

>
I was trying to setup Rclone from your docs, however the latest Rclone no longer has storj on its list. In example you had N 31 which is now Palouse. Do you know which version worked so I can download that?

Now the integration is called Storj gz#16035

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/ZF4LhKRQLskCC5r0Ys1X/how-tos/sync-files-with-rclone/rclone-with-hosted-gateway

**Comment by heunland** [comment]
this can be merged once the remaining comment I left regarding us1 vs AP1 satellite url in example is resolved

**Comment by AlexeyALeonov** [comment]
> 
> should it not say `@asia-east-1.storj.io` instead of `@asia-east-1.tardigrade.io`? (see my comment in gitbook draft)

This is how the rclone configure it ¯\_(ツ)_/¯

**Comment by AlexeyALeonov** [comment]
https://github.com/storj/docs/issues/176#issuecomment-1081965179
this has been updated

**Comment by heunland** [comment]
Changes were merged on gitbook
