### ISSUE TITLE
Node invitation

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#177]
***This ticket was escalated from Zendesk by Helene Unland:***

  **Ticket:** [#16054](https://storj.zendesk.com/agent/tickets/16054)
  **Type:** Ticket
  **Priority:** -
  **Requester:** Raymholt
  **Organization:** -
  **Assignee:** Helene Unland
***

SNO docs section https://docs.storj.io/node/dependencies/identity/#authorize-the-identity needs to be updated.

We no longer send emails when an auth token is requested from https://www.storj.io/host-a-node - The SNO needs to copy the auth token directly from the screen instead.

 gz#16054

**Comment by heunland** [comment]
Specifically, we need to update this sentence so it no longer asks the SNO to check their email:

```
Open your Storj Node invitation email and copy your [single-use authorization token](https://docs.storj.io/node/before-you-begin/auth-token/#authorization-token):
```

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LiiXe2K6q6NwWAdegg5/~/changes/r0O69MO0I8qduF5V5uUT/before-you-begin/auth-token#authorization-token
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LiiXe2K6q6NwWAdegg5/~/changes/r0O69MO0I8qduF5V5uUT/dependencies/identity

**Comment by heunland** [comment]
I fixed the links to point directly to the page where they would see the auth token after entering the email [Node Hosting signup page](https://www.storj.io/host-a-node) and merged
