### ISSUE TITLE
filezilla - update the way how to download the latest version

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#178]
***This ticket was escalated from Zendesk by Aleksey Leonov:***

  **Ticket:** [#16026](https://storj.zendesk.com/agent/tickets/16026)
  **Type:** Ticket
  **Priority:** -
  **Requester:** Tomas
  **Organization:** -
  **Assignee:** Aleksey Leonov
***

I have some troubles with setting my account with filezilla... I dont see any option wit storj, I only  have default FTP/SFTP in Protocol window... do I need Filezilla Pro? What am I doing wrong?

I am using Fedora 35, filezilla installed using flatpak and rpm packege...  none of it has that option... filezilla version 3.58.0

Attachments:<br/> [Screenshot from 2022-03-30 09-41-59.png](https://storj.zendesk.com/attachments/token/qvqPfe590tajmw2vv21u9heOa/?name=Screenshot+from+2022-03-30+09-41-59.png)<br/> [Screenshot from 2022-03-30 09-50-08.png](https://storj.zendesk.com/attachments/token/vRYhfrdOgMrf3oijSU6Z2zzXu/?name=Screenshot+from+2022-03-30+09-50-08.png) gz#16026

**Comment by heunland** [comment]
the instructions in https://docs.storj.io/dcs/how-tos/set-up-filezilla-for-decentralized-file-transfer/#downloading-filezilla need to be clarified so the user will directly download and not use a package manager which may download a version not compatible with Storj DCS protocol

**Comment by heunland** [comment]
@AlexeyALeonov can we close this issue?

**Comment by AlexeyALeonov** [comment]
I think so
