### ISSUE TITLE
Cyberduck integration

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#180]

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/HxOgLu9TW5X8VA1iHlt4/how-tos/how-to-use-cyberduck-and-storj-dcs

**Comment by heunland** [comment]
There are download instructions included in the doc for Linux, but father down we only have sections for "Using CyberDuck with Storj - Windows" and "Using CyberDuck with Storj - Mac" - should there not be a section for Linux also? or a mention that it is similar to Mac maybe?

**Comment by diegocharm** [comment]
Hi all - here is the folder that has all the images that go with the Google Doc (filenames match the comments/callouts in the doc). @AlexeyALeonov I just shared this folder with you. ;)

https://drive.google.com/drive/folders/1ub3ZrbrZnMGYWceLffDLMvMpnW4nPUBt

THANK YOU!

**Comment by heunland** [comment]
"MSI installer for Windows" download link is missing

**Comment by heunland** [comment]
Please see my comments.

**Comment by AlexeyALeonov** [comment]
Updated and replied

**Comment by heunland** [comment]
@AlexeyALeonov regarding the missing screenshot for "Using CyberDuck with Storj - macOS" section, have you looked in the folder https://drive.google.com/drive/folders/1ub3ZrbrZnMGYWceLffDLMvMpnW4nPUBt if the needed screenshot is there? if not, we would need to request @diegocharm to add it to the folder

**Comment by diegocharm** [comment]
Did you find the screen shot? If not, which one specifically is missing and
I'll get it added to the folder. Thanks.

**Comment by heunland** [comment]
@diegocharm it is the first screenshot under the heading of "Using CyberDuck with Storj - macOS" - the current screenshot shows s3.amazonaws.com/ and not gateway.us1.storjshare.io for Server and Nickname and url

**Comment by diegocharm** [comment]
@AlexeyALeonov hi there. Here's the missing/corrected Cyberduck Mac 1 image for this doc. Sorry for the delay!

[CyberDuck MAc pt1_v2](https://user-images.githubusercontent.com/97993222/161782350-8feb0f45-e21c-48ed-9276-a34336b5207f.png)

**Comment by AlexeyALeonov** [comment]
The image has been replaced

**Comment by AlexeyALeonov** [comment]
> There are download instructions included in the doc for Linux, but father down we only have sections for "Using CyberDuck with Storj - Windows" and "Using CyberDuck with Storj - Mac" - should there not be a section for Linux also? or a mention that it is similar to Mac maybe?

There is no GUI version for Linux. Perhaps we need to add instruction, how to configure in CLI (the CLI version is exist for all three platforms).

**Comment by diegocharm** [comment]
The reason we included Mac too was because there were some significant
differences between Win & Mac - not so much difference in Win vs Linux. We
can add Linux later if it is needed, but please don't hold up the posting
for that.

**Comment by heunland** [comment]
reviewed changes and merged
