### ISSUE TITLE
How to Integrate FileZilla Pro with Storj DCS

### ISSUE THREAD

**Issue by diegocharm** [storj/docs#181]
We have a new 'how to' for our docs: How to Integrate FileZilla Pro with Storj DCS to Easily Find, Transfer and Download All of Your Files. You can use this shorter version for a title 'How to Integrate FileZilla Pro with Storj DCS GatewayMT

Please post this new doc right after the 'FileZilla Native Integration'. Can you change the current one (title) to (so they are consistent) How to Integrate FileZilla Standard with Storj DCS Native CLI

Here's the doc:

https://docs.google.com/document/d/1Dqf1y3zk3P3KRcxZ4OJfANTQtvdwkKQ0-QC-BI62dQ8/edit

Here's the folder with all the screen shots: 

[https://drive.google.com/drive/folders/19FBy6ylkbwBUjQ40loF8OR0W9_r86fDG](https://www.google.com/url?q=https://drive.google.com/drive/folders/19FBy6ylkbwBUjQ40loF8OR0W9_r86fDG&sa=D&source=docs&ust=1649351509936495&usg=AOvVaw32ysfj8XTKai_4JGpvUaZ3)

Thanks all!

**Comment by AlexeyALeonov** [comment]
Draft: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/OdtP94ElwMxF9YRbnZyx/how-tos/filezilla-pro-integration-guide#setting-up-regions
Waiting for a normal screenshots for the configuring the FileZillaPro with a GatewayMT section

**Comment by AlexeyALeonov** [comment]
It's ready for review

**Comment by heunland** [comment]
reviewing now

**Comment by heunland** [comment]
I made a bunch of grammar edits and added a few missing hyperlinks.  Merged changes.
