### ISSUE TITLE
Typo in commands to download and install uplink 

### ISSUE THREAD

**Issue by adaRn** [storj/docs#183]
The filenames for downloading and unzipping do not match and this means it cannot be just copypasted. I highlighted it in red rectangles on the screenshots below. Can we edit it?
Link to the docs: https://docs.storj.io/dcs/downloads/download-uplink-cli/

![linux](https://user-images.githubusercontent.com/7052048/163849717-7ec6fa56-256f-4457-98cb-40416ea51bca.png)
![macos](https://user-images.githubusercontent.com/7052048/163849723-091e1161-3553-4a69-90ca-760aeadd4502.png)

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/pD02LdkzLczhWfhLCjZl/downloads/download-uplink-cli
is ready for review and merge
