### ISSUE TITLE
HOT! New 'How To' for new Storj IPFS Pinning Service Beta

### ISSUE THREAD

**Issue by diegocharm** [storj/docs#184]
@heunland @AlexeyALeonov hey there! Here is that very 'hot' (off the press!) How To document to support our IPFS Pinning launch tomorrow. It's been approved by all on the product team - now for your eyes and for publishing.

So sorry for the late notice but this was put together super fast to help stop lots of questions/tickets/etc with our launch tomorrow.

https://docs.google.com/document/d/1gh5EbPst_OQlGVd4nGAY4pin8R4dh8VA8TnPK9dvan0/edit#

As soon as it's posted, we'll add the link to the blog and some other comms. The Press Release for this launch goes live tomorrow at 8 am ET. THANK YOU x 1,000,000.!

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/gWXjI0IMCJMcTYTiyPUL/how-tos/storj-ipfs-pinning-service-beta
is ready for review and merge

**Comment by diegocharm** [comment]
Thanks Helene and everyone!
