### ISSUE TITLE
Bring back original title for FileZilla Pro 'How to' Doc

### ISSUE THREAD

**Issue by diegocharm** [storj/docs#185]
Hi there -

For some reason (?) the headline of this doc got changed when posted. Please update the title to be the title in the doc:

How to Integrate Filezilla Pro with Storj DCS to Easily Find, Transfer and Download All Of Your Files

doc here for reference - https://docs.google.com/document/d/1Dqf1y3zk3P3KRcxZ4OJfANTQtvdwkKQ0-QC-BI62dQ8/edit

Thank you!

**Comment by AlexeyALeonov** [comment]
This headline is too long for the title.
Can it be added as a content description? It will not be showed in the published document, but will be available for crawlers

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/lVVKdRLjdBx3nn6rmMeB/how-tos/filezilla-pro-integration-guide
is ready for review and merge

**Comment by heunland** [comment]
merged
