### ISSUE TITLE
New! How to simplify file management with S3 Browser & Storj DCS

### ISSUE THREAD

**Issue by diegocharm** [storj/docs#186]
Hi all! Here's our third in a 3-part series about the best file management tools to use with Storj DCS. This one is for using S3 + our browser to organize, transfer and manage files in a super easy way.

The Google Doc for this is here: https://docs.google.com/document/d/1xlCKnGqB7Bfeh7N8yQAu86dbDR9tNxRr0WPKl-OuLKw/edit

The screen shots that are referenced in the doc are all included in this folder: https://drive.google.com/drive/folders/1YAXh85Bu6a80QdzGYA5oeL0fjduRjmhM

Let me know if there are any questions and/or concerns. We'll be able to post a couple of cool new blogs (top 3 file management tools; top 3 backup tools) once this is posted.

As always, I so appreciate y'all for reviewing these and getting them posted.

**Comment by AlexeyALeonov** [comment]
You have used a markdown before, please, continue to use it. The content of the google document can be copied only as a one big line without any markups.. So, when you use a markdown - it can be copied normally.

**Comment by AlexeyALeonov** [comment]
The document is calling **Storj Transparency solution brief_2022_07_April**, this is not a guide :)

**Comment by AlexeyALeonov** [comment]
https://docs.google.com/document/d/1xlCKnGqB7Bfeh7N8yQAu86dbDR9tNxRr0WPKl-OuLKw/edit

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/sgqErN3MhTF6kDM0xwEB/how-tos/simplify-file-management-with-s3-browser-and-storj-dcs
is ready for review and merge

**Comment by diegocharm** [comment]
so sorry I posted the wrong doc. Way too many docs open. Thanks @AlexeyALeonov !!

**Comment by heunland** [comment]
Reviewed with grammar and style corrections and merged.
