### ISSUE TITLE
Update Watchtower details

### ISSUE THREAD

**Issue by tempestb** [storj/docs#187]
As I understand it, as of v1.52.2 Watchtower is not used for node updates, but is required for the base image, I want to update the documentation to reflect this change.

**Comment by AlexeyALeonov** [comment]
@tempestb Could you please provide a link to the draft?

**Comment by AlexeyALeonov** [comment]
I believe I have found it: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LiiXe2K6q6NwWAdegg5/~/diff/~/changes/1dxGeAwBJOBHMgrVO99y/setup/cli/software-updates
