### ISSUE TITLE
Move the section Get Started to the top of the Nav bar

### ISSUE THREAD

**Issue by liviolanda** [storj/docs#188]
As a user, I want to see first what I need to Get Started with Storj DCS before learning about concepts and company.

While we don't update the full documentation, I moved the section to the top of the navbar in gitbook, so it's more visible to users. I need this change to be merged.

#188 Moving "Getting Started" section to the top in Navbar
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/m7ojvkjYfVdPL83WhD9m/

**Comment by heunland** [comment]
@liviolanda Please post the link to the gitbook draft that needs to be merged

**Comment by AlexeyALeonov** [comment]
This change is controversial to suggestion to move Downloads up.
See discussion here: https://storj.slack.com/archives/CKTAXNND7/p1631299639007500

**Comment by AlexeyALeonov** [comment]
I guess these two:
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/Tjw6jQrfZYCMAPvzqBP8/getting-started/quickstart-guide
and
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/m7ojvkjYfVdPL83WhD9m/getting-started/quickstart-guide

**Comment by liviolanda** [comment]
@AlexeyALeonov and @heunland I'm gonna close this ticket because we're addressing all these problems together in the new UX. thanks!
