### ISSUE TITLE
[uplink] Update import access commands

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#189]
https://docs.storj.io/dcs/getting-started/quickstart-uplink-cli/uploading-your-first-object/set-up-uplink-cli/
https://docs.storj.io/dcs/api-reference/uplink-cli/import-command/

[See also SUP-797](https://storjlabs.atlassian.net/browse/SUP-797)

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/YS9D04ehRFcR1O3l8Hrq/getting-started/quickstart-uplink-cli/generate-access-grants-and-tokens/generate-a-token
Ready for review and merge

**Comment by heunland** [comment]
reviewing now

**Comment by heunland** [comment]
@AlexeyALeonov please provide clarification what is referred to with "(repeated)" in the description of the flag `--prefix SharePrefix` in the access-restrict section here https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/YS9D04ehRFcR1O3l8Hrq/api-reference/uplink-cli/access-command/access-restrict (see my comment in gitbook draft)

In the section https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/YS9D04ehRFcR1O3l8Hrq/api-reference/uplink-cli/access-command/access-revoke Example for Revoke an access grant, please confirm if it is correct that for the Linux and macOS Usage instructions "access" is repeated twice, while only written once in the command for Windows?
Windows command:
`./uplink.exe access revoke 19hFrjmsi...`
Linux and macOS:
`uplink access access revoke 19hFrjmsi...`
See comment in this section in gitbook

I also see the same thing for Linux and macOS in the Usage Example under the access use section

**Comment by AlexeyALeonov** [comment]
> "(repeated)" in the description of the flag --prefix SharePrefix 

Added example and clarification

> uplink access access revoke 19hFrjmsi...

fixed all such typos

**Comment by heunland** [comment]
I have modified the prefixes description a bit more to clarify. Example is very helpful to illustrate, thank you. 
Changes have been merged.
