### ISSUE TITLE
File redundancy - all images are lost (thanks to GitBook)

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#190]
https://docs.storj.io/dcs/concepts/file-redundancy/

gz#16743

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/dkPXUtxluWMGZ4eO7rHB/concepts/file-redundancy
Ready for review and merge

**Comment by heunland** [comment]
Please add links to the docs where you recovered the missing images from to help with review, thanks

**Comment by AlexeyALeonov** [comment]
Only this page. I do not have an instrument to find them all.

**Comment by heunland** [comment]
I am not sure what you mean by "this page" 
Please tell me which page did you get the images from that you inserted

**Comment by AlexeyALeonov** [comment]
Oh. I misread your message.
I took them from these two blogs:
https://www.storj.io/blog/replication-is-bad-for-decentralized-storage-part-1-erasure-codes-for-fun-and-profit
https://www.storj.io/blog/why-proof-of-replication-is-bad-for-decentralized-storage-part-2-churn-and-burn

**Comment by heunland** [comment]
I fixed some text (this section was taken "as is" from the original blog posts, but for the docs, we need to make references more general so they don't become outdated later.

The images are all correct now. The section was merged.
