### ISSUE TITLE
Update S3 Compatibility Table (server side copy)

### ISSUE THREAD

**Issue by ferristocrat** [storj/docs#193]
**Overview**
With the introduction of Server Side Copy, our S3 compatible gateway now supports the CopyObject method. 

**What is the change?**
[The supported S3 commands page](https://docs.storj.io/dcs/api-reference/s3-compatible-gateway/supported-s3-commands/#supported-s3-commands) should be updated to list `Copy Object` as "Supported."

<img width="1426" alt="Screen Shot 2022-05-05 at 11 33 57 AM" src="https://user-images.githubusercontent.com/7063002/166996016-e7dc2c6a-5f24-4690-950e-6da6c72e380f.png">

**Additional Details**
The following S3 compatibility table that lives within the Gateway-MT repo is up-to-date:
[https://github.com/storj/gateway-st/blob/main/docs/s3-compatibility.md](https://github.com/storj/gateway-st/blob/main/docs/s3-compatibility.md)

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/diff/~/changes/F2lywg3DEJz2M9MkcUJ8/api-reference/s3-compatible-gateway/supported-s3-commands
