### ISSUE TITLE
Create Nextcloud documetation

### ISSUE THREAD

**Issue by tempestb** [storj/docs#199]
https://storj.slack.com/archives/CKTAXNND7/p1652539178139839

Helene Unland
I noticed that we published [this blog](https://www.storj.io/blog/regain-control-and-securely-collaborate-with-nextcloud-and-storj) in April and it links to what I hoped would be instructions on how to set up Nextcloud, instead it just links to https://www.storj.io/solutions/backups which has no info at all about nextcloud. So is the video in the article the only how-to we offer on setting up Nextcloud? There is nothing in our docs, though I thought we had a nextcloud section there before which I can't find anymore now. Should we not add a how-to section for nextcloud in the docs? At a minimum, we should point to the video https://link.us1.storjshare.io/s/jvakv4ddjeprfyi6iqcbrgxy5nda/public/nextcloud-storj-demo.mkv?wrap=1

**Comment by heunland** [comment]
Maybe @tempestb could help update the github page and then add a link to it to our [documentation](https://docs.storj.io) in the how-to section which is where people are probably searching for it.

**Comment by tempestb** [comment]
PR: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/JDzGDpYoItmCYkMRKo5i/

**Comment by AlexeyALeonov** [comment]
merged
