### ISSUE TITLE
Dataverse doc

### ISSUE THREAD

**Issue by amozoss** [storj/docs#202]
A guide to help the Dataverse community configure storj

**Comment by amozoss** [comment]
Draft: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/lGXQ7gG5z4QWeSxepx9J/how-tos/dataverse-integration-guide

**Comment by heunland** [comment]
reviewing now

**Comment by heunland** [comment]
@amozoss I corrected the url for storj signup to https://storj.io/signup & fixed some minor grammar errors.
I added some additional text that I hope will be helpful.  I also added a comment regarding the image for the Access Management. Perhaps you can get an image of what this will be looking like once the API key option will be added from a figma which you can probably request from @iglesiasbrandon or @liviolanda so to avoid having to update this image again soon.

Please review my changes and merge if you accept the changes.

**Comment by heunland** [comment]
I am closing this issue now as the changes have been merged already
