### ISSUE TITLE
Try to fix artifacts of GitBook

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#204]
There are unnecessary `\` at the end of some lines in the produced guide, however, there is no such artifacts in the GitBook source.
For example: https://docs.storj.io/dcs/billing-payment-and-accounts-1/pricing/billing-and-payment/#how-billing-is-calculated, the `\` character at the end of the phrase:
> The following table lists the types of metered services that appear in billing and usage user interfaces as well as invoices:\

The same is going for this phrase on the same page:
> To learn more, check out the [Project Limits](https://docs.storj.io/dcs/concepts/limits/) and [Usage Limit Increases](https://docs.storj.io/dcs/billing-payment-and-accounts-1/pricing/usage-limit-increases/) sections of this Documentation\

* https://docs.storj.io/dcs/billing-payment-and-accounts-1/pricing/free-tier/ has the same issue
* https://docs.storj.io/dcs/billing-payment-and-accounts-1/storj-token/expired-credit-card/
* https://docs.storj.io/dcs/billing-payment-and-accounts-1/storj-token/reporting-a-payment-problem/
* https://docs.storj.io/dcs/billing-payment-and-accounts-1/requesting-a-refund/

etc.

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/IJYlxk1L2Q1k28Yfiab7/billing-payment-and-accounts-1/data-retention-policy
Ready for review and merge

**Comment by heunland** [comment]
@AlexeyALeonov If these changes were included in the same draft with the retention policy #205 then please close this issue as draft for #205 was merged and I checked all the sections that supposedly had changes but couldn´t see where these backslashes were fixed, lets hope it ends up fixed once published in github

**Comment by AlexeyALeonov** [comment]
Fixed more artifacts.
