### ISSUE TITLE
The expired credit card section mention the Data retention policy, but have no link to it

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#205]
https://docs.storj.io/dcs/billing-payment-and-accounts-1/storj-token/expired-credit-card/
The data retention policy is here: https://docs.storj.io/dcs/billing-payment-and-accounts-1/data-retention-policy/

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/IJYlxk1L2Q1k28Yfiab7/billing-payment-and-accounts-1/data-retention-policy
Ready for review and merge

**Comment by heunland** [comment]
while reviewing this I noticed that also links to Terms of Use and Terms of Service were missing in https://docs.storj.io/dcs/billing-payment-and-accounts-1/requesting-a-refund/ so I added them, too and merged the changes.
