### ISSUE TITLE
Add How-To for Arq

### ISSUE THREAD

**Issue by wthorp** [storj/docs#207]
draft https://docs.google.com/document/d/19xxlG0MYjgP_p4MmQxzfmzitItJvDRyXhpTZECew-xA/edit

https://www.arqbackup.com/

**Comment by heunland** [comment]
I found that the gitbook draft to be reviewed is here
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/kZMzZ0R6FS93Lq9UUM8W/how-tos/dataverse-integration-guide

**Comment by heunland** [comment]
@wthorp in reviewing this, I noticed you guide the user to select ¨S3 compatible Server¨ as storage location, even though the dropdown shows ¨Storj¨ as a storage location option. 
Why are we not going to use that option instead, or at least offer it as an alternative? Or do we want customers to use gateway MT only.

I tried configuring Arq with just selecting ¨Storj¨and it also asks for Storj Access Key ID and Storj Access Secret Key, and lets you choose between US1, EU1 and AP1 satellites. See my comment in the gitbook draft. Please consider adding the instructions how to configure by selecting ¨Storj¨ as storage location directly.

For the S3 setup instructions, I added a link to the section that explains how to generate the credentials of Gateway MT as we should not assume the reader knows how to do that: https://docs.storj.io/dcs/getting-started/gateway-mt/#generate-credentials-to-the-gateway-mt
