### ISSUE TITLE
Add How-To for Zerto

### ISSUE THREAD

**Issue by wthorp** [storj/docs#214]
https://www.zerto.com/

**Comment by heunland** [comment]
the draft is here https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/ghQ7cjgLO28cr5AZdQbw/how-tos/zerto-integration-guide

**Comment by heunland** [comment]
reviewing now

**Comment by heunland** [comment]
I left some comments in the draft indicating where a screenshot that shows all fields filled in correctly to configure with Storj S3 Gateway Credentials should be inserted to substitute the screenshot that shows the fields empty. Also farther down there  are 2 screenshots that appear too blurry, please substitute with higher resolution screenshots

I fixed some grammar and style for clarity.

This can be merged once the screenshots have been substituted.

**Comment by heunland** [comment]
I have merged this since it looks like we can´t easily update the screenshots, it is good enough for now.
