### ISSUE TITLE
Create and host Chainstate Snapshots doc

### ISSUE THREAD

**Issue by amozoss** [storj/docs#218]
A guide to help node providers host snapshots on storj

PR: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/JgYQuzlxW8IHXLVgBrnW/how-tos/create-and-host-chainstate-snapshots

**Comment by AlexeyALeonov** [comment]
Reviewed and made some modifications (commit message, images positioning, SNO -> storage nodes).
It's ok for merge, but there would  be a public access grant for sure. If it's not ok, we should update the doc.
