### ISSUE TITLE
Update Photos+ for UI changes

### ISSUE THREAD

**Issue by wthorp** [storj/docs#219]
Per the Photos+ team:

"This looks great, it’s very detailed. One change we’ve made since you made the screenshots is to put all s3-compatible storage providers under one section. This way we’re not indirectly indicating any kind of preference, for example for backblaze over storj. 

So that people don’t get confused, maybe just update the two screenshots from the settings and configure sections that no longer show separate icons for backblaze and Amazon. The rest is the same."

**Comment by wthorp** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/mAOTf3xP22bbwqd7eGNd/how-tos/photos+-integration-guide

**Comment by heunland** [comment]
reviewed and merged
