### ISSUE TITLE
Update Cyberduck screenshots to use gateway.storjshare.io instead of exact one

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#220]
https://docs.storj.io/dcs/how-tos/how-to-use-cyberduck-and-storj-dcs/

**Comment by AlexeyALeonov** [comment]
Draft: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/QcWnbN2fUvMqwQAfXh4a/how-tos/how-to-use-cyberduck-and-storj-dcs
I need screenshots from macOS (I do not have Mac).

**Comment by AlexeyALeonov** [comment]
Updated all screenshots with new flow for accesses
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/QcWnbN2fUvMqwQAfXh4a/

**Comment by heunland** [comment]
Finished reviewing the Cyberduck section (minor edits for grammar). When I switch to Diff View, I see there are a lot of other sections that also show that they have been modified in this same draft, so please do not merge before I finish reviewing those other sections first.

I also reviewed now this section ¨Simplify File Management with S3 Browser and Storj DCS¨ and I left a comment under heading ¨Configuring Storj + S3 Browser¨next to the screenshot that needs to be updated with one that shows all the credentials properly filled out.  I feel like I had mentioned this problem already earlier when reviewing a draft that added this section but looks like the screenshot still is not updated yet.

@AlexeyALeonov  There are still a bunch more sections left to review - DO NOT MERGE, please add the screenshot I mentioned above if you can though.

**Comment by AlexeyALeonov** [comment]
I have added a screenshot with filled out fields

**Comment by heunland** [comment]
Finished reviewing section ¨How to backup your WordPress site with UpdraftPlus to Storj DCS¨ this looks good to go

@AlexeyALeonov for the section ¨How to set up video analytics and video management with Kerberos Vault¨ I think we had not yet updated to gateway.storjshare.io  so the video example needs to be updated I think to not show gateway.eu1.storjshare.io and actually I think the entire workflow is different now for creating S3 credentials so also the text instructions below that video need to be updated accordingly. Maybe we should just get rid of this video and substitute with the same Create S3 credentials instructions we use in the other sections. I left a comment next to the video that I think needed to be updated.

I will continue reviewing more sections later

**Comment by AlexeyALeonov** [comment]
updated Kerberos Vault section

**Comment by heunland** [comment]
Finished reviewing section ¨Store Tesla Sentry Mode & Dashcam videos on Storj DCS¨ - LGTM

**Comment by heunland** [comment]
Finished reviewing Filezilla Pro Integration section

**Comment by AlexeyALeonov** [comment]
Updated, thanks!

**Comment by heunland** [comment]
FInished reviewing Quickstart Guides. Merging the changes now.
