### ISSUE TITLE
Add Peering info to the IPFS Beta docs

### ISSUE THREAD

**Issue by kaloyan-raev** [storj/docs#221]

**Comment by kaloyan-raev** [comment]
Ready for review: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/BDemHoCurHmfXkmFqAW8/how-tos/storj-ipfs-pinning-service-beta

**Comment by AlexeyALeonov** [comment]
Used for review: https://github.com/ipfs/kubo/blob/master/docs/config.md#peeringpeers
