### ISSUE TITLE
Add folder upload example to the IPFS Beta docs

### ISSUE THREAD

**Issue by kaloyan-raev** [storj/docs#222]
We should add a JavaScript example code on how to upload folders.

The example has been already proposed as a solution to a forum user: https://forum.storj.io/t/ipfs-pin-an-existing-cid/19089/12

**Comment by kaloyan-raev** [comment]
Ready for review: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/yrd8iXvvuF2ne1Gipv9l/how-tos/storj-ipfs-pinning-service-beta

For consistency, I also modified the existing JavaScript example for uploading a single file to use the `got` HTTP client too.

**Comment by heunland** [comment]
this has been reviewed and approved by @amozoss - I am merging the changes
