### ISSUE TITLE
[Satellite UI] Update screenshots for new project dashboard

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#223]
https://docs.storj.io/dcs/getting-started/satellite-developer-account/dashboard/

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/qSECfjNN3cXsHNlkNHdP/getting-started/satellite-developer-account/dashboard
ready for review and merge

**Comment by heunland** [comment]
made some grammar fixes in this section and merged
