### ISSUE TITLE
Update STORJ deposit section in Billing

### ISSUE THREAD

**Issue by heunland** [storj/docs#224]
Since we don´t use Coinpayments anymore, we need to update this section of the docs, including screenshots to eliminate references to Coinpayments and substitute with our current manual STORJ deposit workaround

https://docs.storj.io/dcs/billing-payment-and-accounts-1/storj-token/#using-storj-token

**Comment by jenlij** [comment]
At this point we will just update the docs with the new billing flow for native token deposits

**Comment by heunland** [comment]
@jenlij Please note that changes to the docs now need to be made via Archbee, you can ask for details in #guild-documentation on slack

**Comment by AlexeyALeonov** [comment]
updated in https://github.com/storj/docs/issues/229

**Comment by AlexeyALeonov** [comment]
for reference https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/N8HWaLEvRGufG4pdxBQJ/billing-payment-and-accounts-1/storj-token

**Comment by heunland** [comment]
finished review and merged

**Comment by stoweandi** [comment]
Note: updates applied in Archbee
