### ISSUE TITLE
Add google photos import instructions to Photos+ section

### ISSUE THREAD

**Issue by heunland** [storj/docs#225]
add these step by step instructions to the Photos+ section in the docs
https://forum.storj.io/t/how-to-automatically-import-your-google-photos-to-photos-storj/19271?u=heunland

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/gBYHfqUU98LVah2g2q1D/how-tos/photos+-integration-guide
Is ready for review and merge.

**Comment by heunland** [comment]
reviewing this now

**Comment by heunland** [comment]
fixed some formatting and merged
