### ISSUE TITLE
[Satellite UI] Update screenshots for new Billing location

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#229]
https://docs.storj.io/dcs/getting-started/satellite-developer-account/billing/

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/N8HWaLEvRGufG4pdxBQJ/getting-started/satellite-developer-account/my-account/billing
is ready for review and merge.

**Comment by heunland** [comment]
fixed some grammar and style, added some clarification texts and merged
