### ISSUE TITLE
Update Filezilla configuration with new create access wizard

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#231]
https://docs.storj.io/dcs/how-tos/set-up-filezilla-for-decentralized-file-transfer/

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/rbHLcCpODsvOT6XZZiui/how-tos/set-up-filezilla-for-decentralized-file-transfer

is ready for review and merge

**Comment by heunland** [comment]
reviewed and merged

**Comment by stoweandi** [comment]
Note: migrated updates over to Archbee
