### ISSUE TITLE
Create Doc for Immutibility Use Case

### ISSUE THREAD

**Issue by ferristocrat** [storj/docs#246]
For customers who want to ensure immutability we have the ability to create access grants that allow for "write once read many" that would allow customers to achieve immutability (this helps customers looking for object lock/versioning to solve for immutability).

**Comment by NiaStorj** [comment]
@ferristocrat

**Comment by AlexeyALeonov** [comment]
Is it not enough? https://docs.storj.io/learn/concepts/immutability#practical-implementation-pattern
