### ISSUE TITLE
update screenshots to show new free tier limits of 25GB

### ISSUE THREAD

**Issue by heunland** [storj/docs#251]
Please update the screenshots in the following sections to show the new 25GB free tier limits on the sign up screen: https://us1.storj.io/signup

https://docs.storj.io/dcs/how-tos/acronis-integration-guide#gLXmb
https://docs.storj.io/dcs/how-tos/atempo-miria-integration#gLXmb
https://docs.storj.io/dcs/how-tos/elements-integration-guide#gLXmb
https://docs.storj.io/dcs/how-tos/hammerspace-integration-guide#gLXmb
https://docs.storj.io/dcs/iconik-integration#gLXmb
https://docs.storj.io/dcs/how-tos/lucidlink-filespace-integration#gLXmb
https://docs.storj.io/dcs/how-tos/msp360-integration-guide#gLXmb
https://docs.storj.io/dcs/how-tos/splunk-integration-guide#gLXmb
https://docs.storj.io/dcs/how-tos/ix-systems-truenas-integration#FbrLO
https://docs.storj.io/dcs/how-tos/unitrends-integration-guide#gLXmb
https://docs.storj.io/dcs/how-tos/veeam-integration-guide#gLXmb
https://docs.storj.io/dcs/how-tos/video-content-delivery-with-storj-and-livepeer#gLXmb
https://docs.storj.io/dcs/comet-backup-integration-guide#Pmg1q

**Comment by heunland** [comment]
@tempestb indicated he has made these updates, please review and publish @AlexeyALeonov

**Comment by heunland** [comment]
@tempestb could you please give a link to the draft with the changes so that whoever reviews it can find it easily? Thanks

**Comment by tempestb** [comment]
No draft as it was a simple change.  I changed the template and published.  It should now be showing the 25gb screenshot on the docs pages.
