### ISSUE TITLE
Invalid CA for update checks

### ISSUE THREAD

**Issue by sashahilton00** [storj/docs#37]
Seeing the following error on the latest storagenode update:

```
Failed to do periodic version check: %!(EXTRA *url.Error=Get https://version.alpha.storj.io: x509: certificate signed by unknown authority)
```

I should note that my browser resolves the above URL without a problem, and displays a valid cert.

**Comment by stefanbenten** [comment]
@sashahilton00 This is an issue with the docker container.
Its is missing the ca-certificates package internally and thus not able to verify the Lets Encrypt Certificate on the Versioning Server.
This is not critical and will be fixed with the next release.

**Comment by kadamwolfe** [comment]
same.  subscribing.

**Comment by kadamwolfe** [comment]
same.  subscribing.  can we re-open this issue so that the two of us, and anyone else coming here for the same issue, get notified when the fix is release?
