### ISSUE TITLE
Error message about Piecestore protocol

### ISSUE THREAD

**Issue by seamushroon54** [storj/docs#42]
These two error message about Piecestore protocol error showed every several seconds
And the disk usage accumulated to 90gb in the past day.
Not sure is it's a issue or not.
I tried to join the rocket chat but still not getting approved by the admin after 5 days of registration.

![Screenshot_20190412-083828_TeamViewer](https://user-images.githubusercontent.com/49343437/56004729-6f959280-5cff-11e9-8da8-8e499671aa06.jpg)

**Comment by stefanbenten** [comment]
Hey @seamushroon54 
Both of these errors are not critical and technically on the wrong log level.
I will get them changed into the next release, so i will go ahead and close this issue here.
Next time you should also open the issue in our main repo https://github.com/storj/storj
