### ISSUE TITLE
Trying to get help

### ISSUE THREAD

**Issue by Byrd1083** [storj/docs#49]
This is so hard to get going. No GUI? I have been hard drive mining with Burst and Sia and have not had this much issue getting setup. I am attempting to follow the instructions step by step. I have downloaded the identity_windows_amd64.exe. When I open it, It says try running from command prompt. I try that then powershell just flashes but nothing happens. I can not get it to work. I have made all exceptions with windows 10 pro and firewall. There is no reason for it to be blocked. I tried to get on the rocket chat for support. It says I have already signed up with my email as I have in the past. Yet, it says my password is invalid. Not sure how because I use 1password encryption and I can not loose passwords. I try to reset the password. It sends me an email to reset. When I try to it says error something went wrong. I've tried 3 times now with different pass combos and it still just says error. Therefore, I am locked out of rocket chat and I am staring at a brick wall. I really wanted to get on board with this node but you guys have got to make this easier to setup. What do I do from here? I can not install identity_windows_amd64.exe, I can not log into rocket chat, I can not progress forward. I have currently downloaded Docker desktop and that went fine and is running. I can not get identity_windows_amd64.exe to run.

**Comment by stefanbenten** [comment]
Hello @Byrd1083 ,

could you please file a support ticket regarding your rocketchat issues to
support@storj.io?

Besides that, you dont have to install the tool, you have to call if from the powershell with the commands, documented here:
https://github.com/storj/docs/blob/master/Explorer-Release-Setup-Instructions.md

Also please note, that we are in Alpha for the V3 network and we have a big roadmap, that includes improvments for the UI/UX!
