### ISSUE TITLE
Windows binary availability

### ISSUE THREAD

**Issue by Vacilando** [storj/docs#5]
Could you please update this ticket once there's a Windows binary available.

**Comment by Vacilando** [comment]
I suggest you let us know here when the first Windows binary is ready - even if only in beta. I am happy to test but I won't be building it myself.

**Comment by littleskunk** [comment]
You can join us on https://storj.io/community and I will send you the current binary. The binary will be outdated after a few days so we might have to repeat that game a few times.

**Comment by TopperDEL** [comment]
For me the build did work, so I'm fine. But for the Long run the binaries should be Ready-to-use and pre-compiled. This is much more convenient for the average windows-user (that I also am normaly :) ).

**Comment by AlexeyALeonov** [comment]
Windows binaries are available. See https://github.com/storj/storj/releases/latest
