### ISSUE TITLE
Limit watchtower to monitor Storj container only

### ISSUE THREAD

**Issue by meetyg** [storj/docs#53]
When running watchtower as suggested in docs, it monitors (and tries to update) all docker containers running on the host.
I suggest that this be limited to the storagenode container only.
According to https://hub.docker.com/r/containrrr/watchtower, this can be done by passing an argument to the watchtower container with the name(s)of the container to monitor.

So basically all we need is to update the docs accordingly.
i.e.
`docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtower storagenode` <-- added the name of the container to monitor.

**Comment by stefanbenten** [comment]
Hey @meetyg!
There is an existing PR to accomplish this already here: #45 
You might want to collaborate with the Author 👍 

I am closing this issue for now to keep things organized.

**Comment by AlexandrTyshchenko** [comment]
Also please add watchtower to update himself:

`docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtower storagenode watchtower`
