### ISSUE TITLE
docker exec -it storagenode /app/dashboard.sh

### ISSUE THREAD

**Issue by jbdaskie** [storj/docs#56]
Hello

This command works find : docker exec -it storagenode /app/dashboard.sh

The problem is I can't access to the web page : Internal  127.0.0.1:7778
 I suppose I can find my reputation on this page but like I can't acces to it I don't know if it's work well or no.

A last thing, when the docker process to a upgrade like today from v0.10 to v0.11, is the reputation is reset to 0 like the uptime ? I hope no but it to be sure.

Thanks, all the best.

**Comment by stefanbenten** [comment]
Hello @jbdaskie ,

you cannot find your reputation anywhere at this stage. The team is working on this and it will be published in the future.
The Internal Address is also no Web Page and in addition inside of the docker container.

Regarding the upgrade, your reputation is not being reset and you dont have to fear anything if you update within 72 hrs after the release. You can automate this by using the watchtower container, as explained here: [Upgrading your Node via Watchtower](https://github.com/storj/docs/blob/master/Explorer-Release-Setup-Instructions.md#upgrading-your-storage-node)
