### ISSUE TITLE
Windows Workabout...

### ISSUE THREAD

**Issue by azrin619** [storj/docs#61]
After trials and errors...then I found my frigging mistakes...

so this is what I did ..

> docker run -d --restart unless-stopped -p 28967:28967 -e WALLET="0x162C28E126A97D0009158Fbda0cA93E6e9CC13d0" -e EMAIL="azrin@azrin.info" -e ADDRESS="sg-01.azrin.info:4000" -e BANDWIDTH="2TB" -e STORAGE="50GB" -v "C:\\Storagenode\\":/app/identity  -v "C:\\new-storj\\":/app/config --name storagenode storjlabs/storagenode:alpha

Copied IDENTITY to a new directory and found out if I have static IP..then I should rename the -p 28967:28967 to something else on the firewall map...

Windows is a bugger..so ensure c:\\ (DOUBLE BACKSLASH) is needed for paths.. best use a single directory.

-V is your target directory....for stashing and if you have a few HDD lying about..then U may consider resilient drive in Windows 10...

I did [an article in this before.](https://www.azrin.info/2019/03/resilient-file-systems-on-windows-10.html).. short one...

So this is how U combine Drives...

**Comment by stefanbenten** [comment]
Hi @azrin619 ,

we have those information already embeeded into our Documentation

> Note: On Windows you need to format the paths like this: D:\\identity\\storagenode\\ or D:\\data\\

We dont want users to use any kind of RAID or similar. The redundancy of the data is already taken care of at the network layer. If your node dies, the file is not lost.
Also worth noting down, that we are looking into better solutions to make use of multiple HDDs within a single node. But those features are post production release (as not critical).

I will go ahead and close this here, as its not a real issue.
Thanks for your support!
