### ISSUE TITLE
Storage node dashboard impossible to contact , says offline

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [storj/docs#74]
`Storage Node Dashboard ( Node Version: v0.12.2 )

======================

ID           12J3SUuX2bffprM3e5vRZ9Huktv9QLXW1YeV7bpikY2CfpgZjLx
Last Contact OFFLINE
Uptime       1m15s

                   Available       Used     Egress     Ingress
     Bandwidth        5.0 TB     9.8 GB     1.0 GB      8.8 GB (since Jun 1)
          Disk        1.8 TB     2.3 GB

Bootstrap bootstrap.storj.io:8888
Internal  127.0.0.1:7778
External  this.is.my.ip:28967

Neighborhood Size 139`
Here is what the storage node dashboard says
Running on Raspberry pi

**Comment by ifraixedes** [comment]
Have  you change anything in your router, etc.?
Have you tried to restart the container?

**Comment by TomAvecLeVdsl** [comment]
Changed the pi from location , forgeted to port fordward on the router in the new place

Thanks for help

**Comment by ifraixedes** [comment]
Cool, good that you found it out.
