### ISSUE TITLE
Storage Node Setup, Can a signed identity be used by multiple computers at the same time?

### ISSUE THREAD

**Issue by daoying007** [storj/docs#91]

**Comment by stefanbenten** [comment]
@daoying007 It is technically possible to run the same identity on two machines, but they will get traffic which then gets audited on a random basis. This will lead to an inconsistent state in their database (splitted across both). That will disqualify the node ID very, very quickly, as your nodes will fail the audits of data stored on the other machine. On top of that, both machines would constantly update their address in the kademlia network making them basically unavailable the entire time.
